/**
 * SEED DATA
 * ──────────
 * Realistic Thailand-based financial profile for demo purposes.
 * Based on a Bangkok professional with a mortgage, PVD, RMF investments,
 * and various lifestyle expenses.
 */

import { v4 as uuid } from "uuid";
import type {
  Profile, IncomeItem, ExpenseItem, DebtAccount,
  InvestmentAccount, RetirementAssumptions, TaxAssumptions, Scenario,
} from "./types";

const today = new Date();
const thisYear = today.getFullYear();

export const seedProfile: Profile = {
  id: uuid(),
  fullName: "Somchai",
  dateOfBirth: "1990-03-15",          // Age ~36
  retirementAge: 55,
  lifeExpectancy: 90,
  country: "Thailand",
  currency: "THB",
  planningStartDate: `${thisYear}-01-01`,
  maritalStatus: "Single",
  householdNotes: "Bangkok-based IT professional. Owns a condo with mortgage.",
  emergencyFundTargetMonths: 6,
  targetMinCashBalance: 200_000,
  riskProfile: "moderate",
  notes: "Priority: pay off mortgage early. Secondary: build retirement portfolio.",
  currentCashBalance: 350_000,
};

export const seedIncomes: IncomeItem[] = [
  {
    id: uuid(),
    name: "Monthly Salary (After Tax)",
    category: "salary",
    owner: "Somchai",
    frequency: "monthly",
    amount: 85_000,
    startDate: "2021-01-01",
    annualGrowthRate: 0.04,
    isTaxable: false,          // after-tax for cash-flow, gross handled in tax module
    notes: "Demo salary — not real data",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Annual Performance Bonus",
    category: "bonus",
    owner: "Somchai",
    frequency: "yearly",
    amount: 120_000,
    startDate: "2021-01-01",
    annualGrowthRate: 0.03,
    isTaxable: true,
    notes: "Demo bonus — typically paid in Q1",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Freelance / Consulting",
    category: "freelance",
    owner: "Somchai",
    frequency: "monthly",
    amount: 12_000,
    startDate: `${thisYear}-01-01`,
    annualGrowthRate: 0.05,
    isTaxable: true,
    notes: "Demo side income — not real data",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Investment Dividends",
    category: "dividend",
    owner: "Somchai",
    frequency: "yearly",
    amount: 18_000,
    startDate: "2023-01-01",
    annualGrowthRate: 0.03,
    isTaxable: true,
    notes: "Demo dividend income — not real data",
    isActive: true,
  },
];

export const seedExpenses: ExpenseItem[] = [
  {
    id: uuid(), name: "Utilities (Electric, Water)", category: "Utilities",
    amount: 2_500, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: true,
    notes: "Demo — condo utilities", isActive: true, budgetAmount: 2_800,
  },
  {
    id: uuid(), name: "Mobile & Internet", category: "Utilities",
    amount: 1_200, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.02, isEssential: true,
    notes: "Demo — mobile + home fiber", isActive: true, budgetAmount: 1_200,
  },
  {
    id: uuid(), name: "Groceries & Dining", category: "Food",
    amount: 12_000, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.035, isEssential: true,
    notes: "Mix of cooking at home and eating out", isActive: true, budgetAmount: 12_000,
  },
  {
    id: uuid(), name: "Transport (BTS/Grab/Fuel)", category: "Transport",
    amount: 5_000, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: true,
    notes: "Mostly BTS and occasional Grab", isActive: true, budgetAmount: 5_500,
  },
  {
    id: uuid(), name: "Life & Health Insurance", category: "Insurance",
    amount: 30_000, frequency: "yearly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.05, isEssential: true,
    notes: "Term life + health top-up", isActive: true, budgetAmount: 30_000,
  },
  {
    id: uuid(), name: "Condo Common Fee + Maintenance", category: "Housing",
    amount: 4_500, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: true,
    notes: "Monthly common fee + small repairs budget", isActive: true, budgetAmount: 5_000,
  },
  {
    id: uuid(), name: "Subscriptions (Netflix, Spotify, etc.)", category: "Entertainment",
    amount: 1_500, frequency: "monthly", owner: "Somchai",
    startDate: "2021-01-01", inflationRate: 0.05, isEssential: false,
    notes: "Streaming + software subscriptions", isActive: true, budgetAmount: 1_500,
  },
  {
    id: uuid(), name: "Shopping & Personal Care", category: "Shopping",
    amount: 8_000, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: false,
    notes: "Clothes, grooming, misc", isActive: true, budgetAmount: 8_000,
  },
  {
    id: uuid(), name: "Travel (Domestic & International)", category: "Travel",
    amount: 120_000, frequency: "yearly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.04, isEssential: false,
    notes: "2-3 trips per year", isActive: true, budgetAmount: 100_000,
  },
  {
    id: uuid(), name: "Family Support", category: "Family",
    amount: 10_000, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.02, isEssential: true,
    notes: "Monthly support to parents in province", isActive: true, budgetAmount: 10_000,
  },
  {
    id: uuid(), name: "Pet Care (Dog)", category: "Pet",
    amount: 4_000, frequency: "monthly", owner: "Somchai",
    startDate: "2021-06-01", inflationRate: 0.04, isEssential: true,
    notes: "Food, vet, grooming", isActive: true, budgetAmount: 4_000,
  },
  {
    id: uuid(), name: "Gym & Fitness", category: "Health",
    amount: 1_800, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: false,
    notes: "Fitness center membership", isActive: true, budgetAmount: 1_800,
  },
  {
    id: uuid(), name: "Annual Car Service & Registration", category: "Transport",
    amount: 15_000, frequency: "yearly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: true,
    notes: "Car service + annual registration", isActive: true, budgetAmount: 15_000,
  },
  {
    id: uuid(), name: "PVD Contribution (5% salary)", category: "Investment",
    amount: 6_000, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.04, isEssential: true,
    notes: "Employee PVD at 5% of gross ~120K", isActive: true,
  },
  {
    id: uuid(), name: "RMF Annual Investment", category: "Investment",
    amount: 60_000, frequency: "yearly", owner: "Somchai",
    startDate: "2022-01-01", inflationRate: 0.0, isEssential: false,
    notes: "For tax deduction - target max benefit", isActive: true,
  },
];

export const seedDebts: DebtAccount[] = [
  {
    id: uuid(),
    name: "Debt-1 – Primary Home Mortgage",
    lender: "Sample Bank A",
    debtType: "mortgage",
    originalPrincipal: 5_500_000,
    currentBalance: 5_120_000,
    annualInterestRate: 0.035,
    interestType: "floating",
    minimumMonthlyPayment: 32_000,
    standardMonthlyPayment: 32_000,
    extraMonthlyPayment: 0,
    startDate: "2021-01-01",
    loanTermMonths: 360,
    propertyName: "Sample Home",
    annualPrepayment: 0,
    notes: "Primary home mortgage. Demo data — not real.",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Debt-2 – Personal Loan",
    lender: "Sample Bank A",
    debtType: "personal-loan",
    originalPrincipal: 400_000,
    currentBalance: 340_000,
    annualInterestRate: 0.045,
    interestType: "fixed",
    minimumMonthlyPayment: 5_000,
    standardMonthlyPayment: 5_000,
    extraMonthlyPayment: 0,
    startDate: "2023-01-01",
    loanTermMonths: 84,
    notes: "Multi-purpose personal loan. Demo data — not real.",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Debt-3 – Investment Condo Mortgage",
    lender: "Sample Bank B",
    debtType: "mortgage",
    originalPrincipal: 3_200_000,
    currentBalance: 2_850_000,
    annualInterestRate: 0.042,
    interestType: "floating",
    minimumMonthlyPayment: 22_000,
    standardMonthlyPayment: 22_000,
    extraMonthlyPayment: 0,
    startDate: "2022-01-01",
    loanTermMonths: 300,
    propertyName: "Sample Condo",
    notes: "Investment condo mortgage. Demo data — not real.",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Debt-4 – Car Loan",
    lender: "Sample Finance Co.",
    debtType: "personal-loan",
    originalPrincipal: 900_000,
    currentBalance: 620_000,
    annualInterestRate: 0.028,
    interestType: "fixed",
    minimumMonthlyPayment: 15_000,
    standardMonthlyPayment: 15_000,
    extraMonthlyPayment: 0,
    startDate: "2023-06-01",
    loanTermMonths: 72,
    propertyName: "",
    notes: "Car financing loan. Demo data — not real.",
    isActive: true,
  },
];


export const seedInvestments: InvestmentAccount[] = [
  {
    id: uuid(),
    name: "PVD – Company Provident Fund",
    accountType: "PVD",
    assetDescription: "Mixed fund (60% equity / 40% bond)",
    marketValue: 280_000,
    currency: "THB",
    isTaxAdvantaged: true,
    expectedAnnualReturn: 0.06,
    monthlyContribution: 5_000,
    annualContribution: 60_000,
    owner: "Somchai",
    notes: "Demo PVD — 5% employee + 5% employer match",
    isActive: true,
  },
  {
    id: uuid(),
    name: "RMF – Sample RMF Equity Fund",
    accountType: "RMF",
    assetDescription: "Thai equity RMF",
    marketValue: 150_000,
    currency: "THB",
    isTaxAdvantaged: true,
    expectedAnnualReturn: 0.08,
    monthlyContribution: 0,
    annualContribution: 50_000,
    owner: "Somchai",
    notes: "Demo RMF — annual contribution for tax deduction",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Brokerage – Stocks & ETFs",
    accountType: "brokerage",
    assetDescription: "SET50 ETF + individual stocks",
    marketValue: 200_000,
    currency: "THB",
    isTaxAdvantaged: false,
    expectedAnnualReturn: 0.09,
    monthlyContribution: 5_000,
    annualContribution: 60_000,
    owner: "Somchai",
    notes: "Demo brokerage — long-term wealth building",
    isActive: true,
  },
  {
    id: uuid(),
    name: "SSO Savings Account",
    accountType: "SSO",
    assetDescription: "Social Security Office benefit",
    marketValue: 75_000,
    currency: "THB",
    isTaxAdvantaged: true,
    expectedAnnualReturn: 0.03,
    monthlyContribution: 0,
    annualContribution: 0,
    owner: "Somchai",
    notes: "Demo SSO — government contributions",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Emergency Fund (High-Yield Savings)",
    accountType: "savings",
    assetDescription: "High-yield savings account",
    marketValue: 180_000,
    currency: "THB",
    isTaxAdvantaged: false,
    expectedAnnualReturn: 0.015,
    monthlyContribution: 5_000,
    annualContribution: 60_000,
    owner: "Somchai",
    notes: "Demo emergency fund — target 6 months expenses",
    isActive: true,
  },
];

export const seedRetirement: RetirementAssumptions = {
  retirementAge: 55,
  expectedAnnualExpense: 600_000,    // 50K/month in today's money (demo)
  inflationRate: 0.03,
  portfolioReturnPreRetirement: 0.07,
  portfolioReturnDuringRetirement: 0.05,
  safeWithdrawalRate: 0.04,
  pensionMonthlyAmount: 0,
  ssoMonthlyBenefit: 7_500,         // estimated SSO pension
};

export const seedTax: TaxAssumptions = {
  annualGrossIncome: 1_200_000,      // ~100K/month gross (demo data)
  personalDeduction: 60_000,
  employmentIncomeDeduction: 100_000, // capped at 100K
  pvdContribution: 60_000,
  rmfContribution: 50_000,
  ssfContribution: 0,
  lifeInsurancePremium: 20_000,
  healthInsurancePremium: 10_000,
  mortgageInterestDeduction: 50_000, // estimated annual interest portion
  parentalDeduction: 60_000,         // 2 parents × 30,000
  childDeduction: 0,
  otherDeductions: 0,
  annualBonus: 120_000,
};

export const seedScenarios: Scenario[] = [
  {
    id: "base",
    name: "Base Case",
    description: "Current plan: salary growth 4%, inflation 3%, extra 5K/month to mortgage",
    isBase: true,
    color: "#3b82f6",
    assumptions: {
      incomeGrowthRate: 0.04,
      inflationRate: 0.03,
      investmentReturnRate: 0.07,
      mortgageExtraMonthlyPayment: 5_000,
      annualLumpSumPrepayment: 50_000,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "aggressive-paydown",
    name: "Aggressive Mortgage Paydown",
    description: "Pay extra 20,000/month + 100K annual lump sum to accelerate payoff",
    isBase: false,
    color: "#10b981",
    assumptions: {
      incomeGrowthRate: 0.04,
      inflationRate: 0.03,
      investmentReturnRate: 0.05,
      mortgageExtraMonthlyPayment: 20_000,
      annualLumpSumPrepayment: 100_000,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "income-shock",
    name: "Income Shock",
    description: "Job loss / income cut by 50% for 12 months starting next year",
    isBase: false,
    color: "#ef4444",
    assumptions: {
      incomeGrowthRate: 0.02,
      inflationRate: 0.035,
      investmentReturnRate: 0.06,
      mortgageExtraMonthlyPayment: 0,
      annualLumpSumPrepayment: 0,
      incomeShockYear: new Date().getFullYear() + 1,
      incomeShockFactor: 0.5,
      incomeShockDuration: 12,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "refinance-2yr",
    name: "Refinance in 2 Years",
    description: "Refinance mortgage at 5.5% in 2 years, continue extra payments",
    isBase: false,
    color: "#8b5cf6",
    assumptions: {
      incomeGrowthRate: 0.04,
      inflationRate: 0.03,
      investmentReturnRate: 0.07,
      mortgageExtraMonthlyPayment: 5_000,
      refinanceYear: new Date().getFullYear() + 2,
      refinanceRate: 0.055,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "retirement-first",
    name: "Retirement First",
    description: "Maximize investment contributions, reduce extra mortgage payment",
    isBase: false,
    color: "#f59e0b",
    assumptions: {
      incomeGrowthRate: 0.04,
      inflationRate: 0.03,
      investmentReturnRate: 0.09,
      mortgageExtraMonthlyPayment: 0,
      annualLumpSumPrepayment: 0,
      taxReliefInvestmentAmount: 200_000,
    },
    createdAt: new Date().toISOString(),
  },
];
