/**
 * TOY REAL DATA – Authoritative snapshot of Toy Theeranan's financial profile.
 * Sourced from: financial-plan backup.json (2026-04-15)
 *
 * Used by initUsers() to seed fp_data_toy localStorage on first load,
 * and to restore it when demo/seed data is detected in the admin namespace.
 */

export const toyRealData = {
  profile: {
    id: "6e5f6a78-8628-4c06-8f1e-9e7cd57b986d",
    fullName: "Toy",
    dateOfBirth: "1985-04-16",
    retirementAge: 60,
    lifeExpectancy: 90,
    country: "Thailand",
    currency: "THB",
    planningStartDate: "2026-04-15",
    maritalStatus: "Single",
    householdNotes: "Bangkok-based professional. Owns a condo with mortgage.",
    emergencyFundTargetMonths: 6,
    targetMinCashBalance: 100000,
    riskProfile: "moderate",
    notes: "Priority: increase RMF to support with Thailand tax reduction campaign. pay off mortgage early. Secondary: build retirement portfolio.",
    currentCashBalance: 15000,
  },
  incomes: [
    {
      id: "4109b869-8bd3-4506-8c9e-f22733473255",
      name: "Monthly Salary (After Tax)",
      category: "salary",
      owner: "Toy",
      frequency: "monthly",
      amount: 170000,
      startDate: "2026-03-25",
      annualGrowthRate: 0.04,
      isTaxable: true,
      notes: "Senior role, annual 4% increment expectation",
      isActive: true,
    },
    {
      id: "2098b1eb-f8c8-4800-8d1d-a20795385bcb",
      name: "STI",
      category: "bonus",
      owner: "Toy",
      frequency: "yearly",
      amount: 300000,
      startDate: "2020-01-01",
      annualGrowthRate: 0.04,
      isTaxable: true,
      notes: "Typically paid in Q1 15% ",
      isActive: true,
    },
    {
      id: "2f5e555f-4dfc-4e1c-80ee-538feaec28c9",
      name: "Whizdom Rental Income",
      category: "rental",
      owner: "Toy",
      frequency: "monthly",
      amount: 18000,
      startDate: "2026-03-25",
      annualGrowthRate: 0,
      isTaxable: false,
      notes: "",
      isActive: true,
    },
    {
      id: "6b7d29d6-74ff-4ab3-83de-061cb9fc5688",
      name: "Dec Bonus",
      category: "bonus",
      owner: "Toy",
      frequency: "yearly",
      amount: 170000,
      startDate: "2026-04-15",
      annualGrowthRate: 0.04,
      isTaxable: true,
      notes: "",
      isActive: true,
    },
  ],
  expenses: [
    {
      id: "0080eb2a-d873-4bf7-a7a2-604ef9046793",
      name: "Utilities (Electric, Water)",
      category: "Utilities",
      amount: 2500,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.03,
      isEssential: true,
      notes: "Condo utilities",
      isActive: true,
      budgetAmount: 2800,
    },
    {
      id: "a77d80f8-b1f9-4ff1-a508-bc2cfe97735b",
      name: "Mobile & Internet",
      category: "Utilities",
      amount: 1200,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.02,
      isEssential: true,
      notes: "AIS 5G + home fiber",
      isActive: true,
      budgetAmount: 1200,
    },
    {
      id: "fed55915-0bb5-46ca-8b0a-072ef5520af0",
      name: "Groceries & Dining",
      category: "Food",
      amount: 12000,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.035,
      isEssential: true,
      notes: "Mix of cooking at home and eating out",
      isActive: true,
      budgetAmount: 12000,
    },
    {
      id: "f8a2eac6-4531-49d9-82bd-a431c87f613f",
      name: "Transport (BTS/Grab/Fuel)",
      category: "Transport",
      amount: 5000,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.03,
      isEssential: true,
      notes: "Mostly BTS and occasional Grab",
      isActive: true,
      budgetAmount: 5500,
    },
    {
      id: "2e3aad3d-8993-48da-aa3a-ba19af842d14",
      name: "Life & Health Insurance",
      category: "Insurance",
      amount: 30000,
      frequency: "yearly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.05,
      isEssential: true,
      notes: "Term life + health top-up",
      isActive: true,
      budgetAmount: 30000,
    },
    {
      id: "12d4012b-ddcc-477e-9ad6-f549d0c77483",
      name: "Condo Common Fee + Maintenance",
      category: "Housing",
      amount: 4500,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.03,
      isEssential: true,
      notes: "Monthly common fee + small repairs budget",
      isActive: true,
      budgetAmount: 5000,
    },
    {
      id: "5ebc832d-b60a-4254-b479-928c0f5855f8",
      name: "Subscriptions (Netflix, Spotify, etc.)",
      category: "Entertainment",
      amount: 1500,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2021-01-01",
      inflationRate: 0.05,
      isEssential: false,
      notes: "Streaming + software subscriptions",
      isActive: true,
      budgetAmount: 1500,
    },
    {
      id: "c6b6114b-b786-45b5-ac3b-390f7da6f1f7",
      name: "Shopping & Personal Care",
      category: "Shopping",
      amount: 8000,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.03,
      isEssential: false,
      notes: "Clothes, grooming, misc",
      isActive: true,
      budgetAmount: 8000,
    },
    {
      id: "969bf1b0-1ef6-4734-b1f7-263145a4dcef",
      name: "Travel (Domestic & International)",
      category: "Travel",
      amount: 120000,
      frequency: "yearly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.04,
      isEssential: false,
      notes: "2-3 trips per year",
      isActive: true,
      budgetAmount: 100000,
    },
    {
      id: "3187d0fc-a010-47a9-bdb3-e1a8198fbaba",
      name: "Family Support",
      category: "Family",
      amount: 10000,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.02,
      isEssential: true,
      notes: "Monthly support to parents in province",
      isActive: true,
      budgetAmount: 10000,
    },
    {
      id: "8d0d1526-6bbc-4b0c-8006-b88089d6e9a4",
      name: "Pet Care (Dog)",
      category: "Pet",
      amount: 4000,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2021-06-01",
      inflationRate: 0.04,
      isEssential: true,
      notes: "Food, vet, grooming",
      isActive: true,
      budgetAmount: 4000,
    },
    {
      id: "b226d544-d2af-4980-a488-dbd98c08c206",
      name: "Gym & Fitness",
      category: "Health",
      amount: 1800,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.03,
      isEssential: false,
      notes: "Fitness center membership",
      isActive: true,
      budgetAmount: 1800,
    },
    {
      id: "d877167e-9b44-4993-b524-5bf32fed3838",
      name: "Annual Car Service & Registration",
      category: "Transport",
      amount: 15000,
      frequency: "yearly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.03,
      isEssential: true,
      notes: "Car service + annual registration",
      isActive: true,
      budgetAmount: 15000,
    },
    {
      id: "7292849b-02cf-4962-a74c-d3f8bb550ebc",
      name: "PVD Contribution (5% salary)",
      category: "Investment",
      amount: 6000,
      frequency: "monthly",
      owner: "Toy",
      startDate: "2020-01-01",
      inflationRate: 0.04,
      isEssential: true,
      notes: "Employee PVD at 5% of gross ~120K",
      isActive: true,
    },
    {
      id: "4665faf2-46b3-4117-9f72-40502eeb63d2",
      name: "RMF Annual Investment",
      category: "Investment",
      amount: 60000,
      frequency: "yearly",
      owner: "Toy",
      startDate: "2022-01-01",
      inflationRate: 0,
      isEssential: false,
      notes: "For tax deduction - target max benefit",
      isActive: true,
    },
  ],
  debts: [
    {
      id: "be8120d1-772c-4044-b51a-e02adb0d0f44",
      name: "Debt-1 – Main Thawee (KKP Mortgage)",
      lender: "KKP Bank (Kiatnakin Phatra)",
      debtType: "mortgage",
      originalPrincipal: 9610000,
      currentBalance: 9204261,
      annualInterestRate: 0.032,
      interestType: "fixed",
      minimumMonthlyPayment: 38900,
      standardMonthlyPayment: 38900,
      extraMonthlyPayment: 0,
      startDate: "2026-04-01",
      loanTermMonths: 360,
      propertyName: "Thawee House",
      annualPrepayment: 0,
      notes: "Main mortgage on Thawee property. Annual interest 2025: ฿297,309. Principal paid 2025: ฿302,691.",
      isActive: true,
    },
    {
      id: "013a9776-547f-4b61-8ef9-545464300165",
      name: "Debt-2 – Multi Purpose Loan Thawee (KKP)",
      lender: "KKP Bank (Kiatnakin Phatra)",
      debtType: "personal-loan",
      originalPrincipal: 510000,
      currentBalance: 448927,
      annualInterestRate: 0.032,
      interestType: "floating",
      minimumMonthlyPayment: 3900,
      standardMonthlyPayment: 3900,
      extraMonthlyPayment: 0,
      startDate: "2026-04-01",
      loanTermMonths: 120,
      notes: "Multi-purpose loan secured on Thawee property. Annual interest 2025: ฿14,821.",
      isActive: true,
    },
    {
      id: "e555b10b-0619-4fd8-8c8b-f0ad4ffbc971",
      name: "Debt-3 – CIMB Greenville Mortgage",
      lender: "CIMB Bank Thailand",
      debtType: "mortgage",
      originalPrincipal: 4530000,
      currentBalance: 4113488,
      annualInterestRate: 0.0499,
      interestType: "floating",
      minimumMonthlyPayment: 19000,
      standardMonthlyPayment: 19000,
      extraMonthlyPayment: 0,
      startDate: "2026-04-01",
      loanTermMonths: 300,
      propertyName: "Greenville",
      notes: "CIMB mortgage on Greenville property. Annual interest 2025: ฿209,470. Highest rate – consider refinance.",
      isActive: true,
    },
    {
      id: "7e0a10f2-7c7b-4bd3-b406-24b906040cc0",
      name: "Debt-4 – LH Whizdom Mortgage",
      lender: "Land and Houses Bank (LH Bank)",
      debtType: "mortgage",
      originalPrincipal: 2550000,
      currentBalance: 2270718,
      annualInterestRate: 0.03,
      interestType: "floating",
      minimumMonthlyPayment: 20000,
      standardMonthlyPayment: 20000,
      extraMonthlyPayment: 0,
      startDate: "2026-04-01",
      loanTermMonths: 240,
      propertyName: "Whizdom",
      notes: "LH Bank mortgage on Whizdom condo. Rental income (฿18,000/mo) partially offsets payments. Lowest rate at 3.00%.",
      isActive: true,
    },
  ],
  investments: [
    {
      id: "29cffca6-0568-4102-94e4-fd1b20f6a148",
      name: "PVD – Company Provident Fund",
      accountType: "PVD",
      assetDescription: "Mixed fund (60% equity / 40% bond)",
      marketValue: 3200000,
      currency: "THB",
      isTaxAdvantaged: true,
      expectedAnnualReturn: 0.04,
      monthlyContribution: 50000,
      annualContribution: 60000,
      owner: "Toy",
      notes: "",
      isActive: true,
    },
    {
      id: "f444b99e-d59d-43d0-9fb6-9627fe7a7f35",
      name: "RMF – SCBGOLDHRMF",
      accountType: "RMF",
      assetDescription: "",
      marketValue: 338513,
      currency: "THB",
      isTaxAdvantaged: true,
      expectedAnnualReturn: 0.1,
      monthlyContribution: 0,
      annualContribution: 250000,
      owner: "Toy",
      notes: "Performance of FY25/26 is at +34% or 87K earned",
      isActive: true,
    },
    {
      id: "a49c04a1-df0c-4412-8ee0-028c1e9cdd14",
      name: "SSO Savings Account",
      accountType: "SSO",
      assetDescription: "Social Security Office benefit",
      marketValue: 171597,
      currency: "THB",
      isTaxAdvantaged: true,
      expectedAnnualReturn: 0.03,
      monthlyContribution: 1750,
      annualContribution: 0,
      owner: "Toy",
      notes: "Government SSO contributions tracked separately",
      isActive: true,
    },
  ],
  retirement: {
    retirementAge: 55,
    expectedAnnualExpense: 720000,
    inflationRate: 0.03,
    portfolioReturnPreRetirement: 0.07,
    portfolioReturnDuringRetirement: 0.05,
    safeWithdrawalRate: 0.04,
    pensionMonthlyAmount: 0,
    ssoMonthlyBenefit: 7500,
  },
  tax: {
    annualGrossIncome: 1560000,
    personalDeduction: 60000,
    employmentIncomeDeduction: 100000,
    pvdContribution: 72000,
    rmfContribution: 250000,
    ssfContribution: 0,
    lifeInsurancePremium: 25000,
    healthInsurancePremium: 15000,
    mortgageInterestDeduction: 60000,
    parentalDeduction: 60000,
    childDeduction: 0,
    otherDeductions: 0,
    annualBonus: 180000,
  },
  scenarios: [
    {
      id: "base",
      name: "Base Case",
      description: "Current plan: salary growth 4%, inflation 3%, extra 5K/month to mortgage",
      isBase: true,
      color: "#3b82f6",
      assumptions: {
        incomeGrowthRate: 0.04,
        inflationRate: 0.03,
        investmentReturnRate: 0.07,
        mortgageExtraMonthlyPayment: 5000,
        annualLumpSumPrepayment: 50000,
      },
      createdAt: "2026-04-15T14:08:17.761Z",
    },
    {
      id: "aggressive-paydown",
      name: "Aggressive Mortgage Paydown",
      description: "Pay extra 20,000/month + 100K annual lump sum to accelerate payoff",
      isBase: false,
      color: "#10b981",
      assumptions: {
        incomeGrowthRate: 0.04,
        inflationRate: 0.03,
        investmentReturnRate: 0.05,
        mortgageExtraMonthlyPayment: 20000,
        annualLumpSumPrepayment: 100000,
      },
      createdAt: "2026-04-15T14:08:17.761Z",
    },
    {
      id: "income-shock",
      name: "Income Shock",
      description: "Job loss / income cut by 50% for 12 months starting next year",
      isBase: false,
      color: "#ef4444",
      assumptions: {
        incomeGrowthRate: 0.02,
        inflationRate: 0.035,
        investmentReturnRate: 0.06,
        mortgageExtraMonthlyPayment: 0,
        annualLumpSumPrepayment: 0,
        incomeShockYear: 2027,
        incomeShockFactor: 0.5,
        incomeShockDuration: 12,
      },
      createdAt: "2026-04-15T14:08:17.761Z",
    },
    {
      id: "refinance-2yr",
      name: "Refinance in 2 Years",
      description: "Refinance mortgage at 5.5% in 2 years, continue extra payments",
      isBase: false,
      color: "#8b5cf6",
      assumptions: {
        incomeGrowthRate: 0.04,
        inflationRate: 0.03,
        investmentReturnRate: 0.07,
        mortgageExtraMonthlyPayment: 5000,
        refinanceYear: 2028,
        refinanceRate: 0.055,
      },
      createdAt: "2026-04-15T14:08:17.761Z",
    },
    {
      id: "retirement-first",
      name: "Retirement First",
      description: "Maximize investment contributions, reduce extra mortgage payment",
      isBase: false,
      color: "#f59e0b",
      assumptions: {
        incomeGrowthRate: 0.04,
        inflationRate: 0.03,
        investmentReturnRate: 0.09,
        mortgageExtraMonthlyPayment: 0,
        annualLumpSumPrepayment: 0,
        taxReliefInvestmentAmount: 200000,
      },
      createdAt: "2026-04-15T14:08:17.761Z",
    },
  ],
  activeScenarioId: "base",
};

/**
 * Detects whether a stored data blob looks like demo/seed data
 * (i.e., it was contaminated by loadSeedData or a demo snapshot).
 */
export function looksLikeDemoData(data: any): boolean {
  if (!data?.profile) return false;
  const name = data.profile.fullName?.toLowerCase() ?? "";
  return name === "somchai" || name === "demo user" || name === "";
}
